server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI4G5Svnb2TWBMuKnNT6jY
    keySecret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    bucketName: srb-file-200921